services:
  api:
    build: .

    container_name: API-Server

    ports:
      - "3000:3000"

    environment:
      # The Dockerfile uses doppler to provision secrets for runtime and the docker service currently requires a doppler setup to run
      # We intend to change the container to be runnable without doppler, but currently not a priority
      - DOPPLER_TOKEN=[INSERT_TOKEN_HERE]
      # Specify the database URI to use for mongo, either local, remote, or its own container
      - DATABASE_URI=mongodb://mongodb:27017
      # Specify the database name to use
      - DBNAME=SimplyPlural
      # Specify whether to run local events (reminders, front change notifications, etc.)
      - LOCALEVENTS=true
      - NODE_ENV=development
      - DEVELOPMENT=true
      - NO_LOGS=true

  mongodb:
    image: mongo
    container_name: API-Mongodb
    ports:
      - "27017:27017"
    # Uncomment this if you wish to persist the database
    #volumes:
    # - data-volume:/data/db

volumes:
  data-volume:
